{
 "title": "Auth Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Login Attempts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_login_attempts_total{status=\"success\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "auth_login_attempts_total{status=\"failure\"}",
     "legendFormat": "__auto"
    },
    { "expr": "auth_login_attempts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Token Statistics",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "auth_token_generated_total{type=\"access\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "auth_token_generated_total{type=\"refresh\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(auth_login_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, rate(auth_login_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, rate(auth_login_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(grpc_request_total{status=~\"success\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(grpc_request_total{status=\"error\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}